Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Controllers/BaseController.cs
using Nhom8_ShopMotoBikes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nhom8_ShopMotoBikes.Controllers
{
    public class BaseController : Controller
    {

        private ShopMotoBikes db = new ShopMotoBikes();
        public PartialViewResult _Navbar()
        {
            var danhMucs = db.DanhMucs.Select(n => n);

            ViewBag.SoLuongGioHang = this.TongSoLuong();
            return PartialView(danhMucs);
        }
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }

    }
}

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom8_ShopMotoBikes.Models;

using PagedList;

namespace Nhom8_ShopMotoBikes.Controllers
{
    public class DanhMucsController : Controller
    {
        private ShopMotoBikes db = new ShopMotoBikes();

        // GET: DanhMucs/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return Redirect("/NotFound/Index");
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                //return HttpNotFound();
                return Redirect("/NotFound/Index");
            }
            var hangs = db.Hangs.Where(p => p.DanhMuc.MaDM == id).OrderByDescending(p => p.MaHang);
            ViewBag.DanhMuc = danhMuc;

            int pageSizeFix = 8; //Kích thước trang
            int pageNumber = (page ?? 1);

            return View(hangs.ToPagedList(pageNumber, pageSizeFix));
           
        }

        
    }
}

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Controllers/TaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom8_ShopMotoBikes.Models;

namespace Nhom8_ShopMotoBikes.Controllers
{
    public class TaiKhoansController : Controller
    {
        private ShopMotoBikes db = new ShopMotoBikes();

        public ActionResult Logout()
        {
            Session["user"] = null;
            return Redirect("/");
        }

        public ActionResult Login()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection frm)
        {
            if (ModelState.IsValid)
            {
                string email = frm["email"];
                string password = frm["password"];

                TaiKhoan user = db.TaiKhoans.Where(s => s.Email.Equals(email) && s.MatKhau.Equals(password)).SingleOrDefault();
                if (user != null )
                {
                    if (user.TrangThai)
                    {
                        Session["user"] = user;
                        return Redirect("/");
                    }
                    else
                    {
                        ViewBag.errorLogin = "Tài khoản của bạn đang bị khóa";
                    }
                }
                else
                {
                    ViewBag.errorLogin = "Vui lòng kiểm tra lại email hoặc mật khẩu! ";
                }

            }
            return View();
        }

        public ActionResult Register()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "MaTK,TenDN,HoTen,SoDienThoai,Email,MatKhau")] TaiKhoan taiKhoan, FormCollection frm)
        {
            try
            {
                string confirmPassword = frm["confirmPassword"];
                if (confirmPassword != taiKhoan.MatKhau)
                {
                    ViewBag.errorRegister = "Mật khẩu xác nhận không khớp! ";
                    return View(taiKhoan);
                }

                var tkcheck = db.TaiKhoans.Where(tk => tk.Email == taiKhoan.Email || tk.TenDN == taiKhoan.TenDN);
                if (tkcheck.Count() == 0)
                {
                    if (ModelState.IsValid)
                    {
                        taiKhoan.TrangThai = true;
                        db.TaiKhoans.Add(taiKhoan);
                        db.SaveChanges();

                    }
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.errorRegister = "Tên đăng nhập hoặc email đã tồn tại! ";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.errorRegister = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
            

        }


        public ActionResult ThongTin()
        {
            if (Session["user"] != null)
            {
                TaiKhoan taiKhoan = Session["user"] as TaiKhoan;
                List<DonHang> listDonHang = db.DonHangs.Where(p => p.MaTK == taiKhoan.MaTK).ToList();

                ViewBag.listDonHangByMaTK = listDonHang;

                return View(taiKhoan);
            }
            return Redirect("/");
            
            
        }
        public ActionResult SuaTaiKhoan()
        {
            if (Session["user"] != null)
            {
                TaiKhoan taiKhoan = Session["user"] as TaiKhoan;
                return View(taiKhoan);
            }
            return Redirect("/");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaTaiKhoan([Bind(Include = "MaTK,TenDN,HoTen,SoDienThoai,Email,MatKhau,TrangThai,Quyen")] TaiKhoan taiKhoan)
        {
            try
            {
                var tkcheck = db.TaiKhoans.Where(tk => (tk.Email == taiKhoan.Email || tk.TenDN == taiKhoan.TenDN) && tk.MaTK != taiKhoan.MaTK);
                if (tkcheck.Count() == 0 )
                {
                    db.Entry(taiKhoan).State = EntityState.Modified;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                    Session["user"] = taiKhoan;

                    return RedirectToAction("ThongTin");
                }
                else
                {
                    ViewBag.errorUpdateTaikhoan = "Tên đăng nhập hoặc email đã tồn tại! ";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
            ViewBag.errorUpdateTaikhoan = "Lỗi " + ex.Message;
            return View(taiKhoan);
            }


        }

        public ActionResult SuaMatKhau()
        {
            if (Session["user"] != null)
            {
                TaiKhoan taiKhoan = Session["user"] as TaiKhoan;
                return View(taiKhoan);
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaMatKhau([Bind(Include = "MaTK,TenDN,HoTen,SoDienThoai,Email,MatKhau,TrangThai,Quyen")] TaiKhoan taiKhoan, FormCollection frm)
        {
            try
            {
                string cu = Request["oldPassword"];
                string moi = Request["newPassword"];
                string xacnhan = Request["confirmPassword"];

                if (cu != null && moi != null && xacnhan != null)
                {
                    if (cu != "" && moi != "" && xacnhan != "")
                    {
                        if (moi == xacnhan)
                        {
                            if (moi.Length >= 3 && moi.Length <= 30)
                            {
                                TaiKhoan tk = Session["user"] as TaiKhoan;
                                if (cu == tk.MatKhau + "")
                                {
                                    taiKhoan.MatKhau = moi;
                                    db.Entry(taiKhoan).State = EntityState.Modified;
                                    Session["user"] = taiKhoan;
                                    db.SaveChanges();
                                    return RedirectToAction("ThongTin");

                                }
                                else
                                {
                                    ViewBag.LoiMatKhau = "Mật khẩu cũ không khớp!";
                                    return View(taiKhoan);
                                }
                            }
                            else
                            {
                                ViewBag.LoiMatKhau = "Độ dài mật khẩu mới >=3 và <=30!";
                                return View(taiKhoan);
                            }

                        }
                        else
                        {
                            ViewBag.LoiMatKhau = "Mật khẩu mới và xác nhận không khớp!";
                            return View(taiKhoan);
                        }
                    }
                    else
                    {
                        ViewBag.LoiMatKhau = "Không được để trống trường dữ liệu nào!";
                        return View(taiKhoan);
                    }
                }
                else
                {
                    ViewBag.LoiMatKhau = "Không được để trống trường dữ liệu nào!";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {

                ViewBag.LoiMatKhau = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
           



        }





    }
}

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Views/Shared/_Footer.cshtml
<!-- ======= Footer ======= -->
<div class="grocino-footer2" style="background-image: url(/wwwroot/img/slide/footer_bg.jpg); background-repeat: no-repeat; background-size: contain; background-position: center;">
    <div id="grocino-footer" class="footer-container">
        <div class="grocino-footer-row">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6 mr-auto">
                        <div class="grocino-second-row-item">
                            <a href="index.html">
                                <img src="~/wwwroot/img/slide/logo2.jpg" alt="HoangCau" title="HoangCau" class="img-fluid logo" />
                            </a>
                            <p>
                                HỆ THỐNG XE MÁY HOÀNG CẦU chuyên cung cấp các dòng xe Honda, Yamaha, SYM, Suzuki, xe
                                nhập khẩu,.... chính hãng, cam kết mang đến những sản phẩm, phụ tùng chất lượng nhất đến
                                tay người tiêu dùng.
                            </p>
                        </div>
                    </div>

                    <div>
                        <div class="footer_showroom">
                            <h4>HỆ THỐNG SHOWROOM</h4>
                            <ul>
                                <li>
                                    <a href="@Url.Action("Index","Home")">
                                        <strong>YAMAHA TOWN HOÀNG CẦU - 08 </strong><br>
                                        ☎:0274 6568 777 📞: 0989 882 545<br>
                                        ĐC: Số 189, Đường Nguyễn Trãi, P. Dĩ An, Thị Xã Dĩ An, Tỉnh Bình Dương.
                                    </a></a>
                                </li>
                                <br>
                                <li>
                                    <a href="@Url.Action("Index","Home")">
                                        <strong>HOÀNG CẦU CHI NHÁNH 2 </strong><br>
                                        ☎:02854 432 212 📞: 0984 741 875 <br>
                                        ĐC: Số 7-9, QL 1K, P. Linh Xuân, Thủ Đức, Tp. HCM.
                                    </a></a>
                                </li>
                                <br>
                                <li>
                                    <a href="@Url.Action("Index","Home")">
                                        <strong>HOÀNG CẦU CHI NHÁNH 3</strong><br>
                                        ☎:02854 034 142 📞: 0989 882 545<br>
                                        ĐC: 123/2A Ngô Chí Quốc, KP.2, P.Bình Chiểu, Q.Thủ Đức, TP.HCM.
                                    </a></a>
                                </li>
                                <br>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="grocino-second-row-item">
                            <h4>LIÊN KẾT NHANH</h4>
                            <ul>
                                @if (Session["user"] == null)
                                {
                                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                                    <li>@Html.ActionLink("Đăng nhập", "Login", "TaiKhoans")</li>
                                    <li>@Html.ActionLink("Đăng ký", "Register", "TaiKhoans")</li>
                                }
                                else
                                {
                                    
                                    <li>@Html.ActionLink("Sửa tài khoản", "SuaTaiKhoan", "TaiKhoans")</li>
                                    <li>@Html.ActionLink("Đổi mật khẩu", "SuaMatKhau", "TaiKhoans")</li>
                                    <li>@Html.ActionLink("Đăng xuất", "Logout", "TaiKhoans")</li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div>
        <div class="copyright">
            Copyright  <i class="far fa-copyright"></i> 2021 Nhóm 8 - Lập trình ASP.NET
        </div>
    </div>
</div>
<!-- End Footer -->

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">


<!-- Mirrored from ocsolutions.co.in/grocerino/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 12 Oct 2021 14:16:18 GMT -->
<head>

    <title>Hệ Thống Xe máy Hoàng Cầu</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, shrink-to-fit=9" />

    <meta name="description" content="Home supermarket" />

    <meta name="author" content="Home Grocerino" />

    <link rel="icon" type="image/png" href="~/wwwroot/img/logos/logo1.jpg" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @{Html.RenderPartial("_Style");}


</head>

<body class="grocino-home">




    <!-- Top header start -->
    @{ Html.RenderAction("_Navbar", "Base"); }
    <!-- Start Hero Slide-->
   

    @RenderBody()

    <!-- footer -->
    <!-- End Hero Slide-->
    <!-- About us start -->
    <!-- About us end -->
    <!-- grocino footer start -->
    <!-- ======= Footer ======= -->
    @Html.Partial("_Footer")
    <!-- End Footer -->
    <!-- mobile menu End -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    
    <!-- JS -->
    @{Html.RenderPartial("_Script");}

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GF3SVYD2YD"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-GF3SVYD2YD');
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>


<!-- Mirrored from ocsolutions.co.in/grocerino/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 12 Oct 2021 14:17:01 GMT -->
</html>

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Views/Shared/_Navbar.cshtml
@model IEnumerable<Nhom8_ShopMotoBikes.Models.DanhMuc>




<header id="header" class="fixed-top">
        <div class="p1">
            <div class="container d-flex align-items-center">
                <a href="@Url.Action("Index","Home")" class="logo me-auto"><img src="~/wwwroot/img/logos/logo1.png" alt="" width="100%" height="100%"></a>

            </div>
        </div>
        <div class="p2">
            <ul id="menu">
                <div class="inner">
                    <div class="header-navbar-wrapper">
                        <div class="header-navbar text-right">
                            <ul class="no-bullets">
                                <li><a href="@Url.Action("Index", "Home")"><span>TRANG CHỦ</span></a></li>
                                <li>
                                    <a href="#"><span>SẢN PHẨM</span><i class="bi bi-chevron-down"></i></a>
                                    <ul style="margin-left: -117px;">
                                       
                    
                                        @foreach (var item in Model)
                                        {
                                         <li><a href="@Url.Action("Details","DanhMucs",new { id = item.MaDM})"><span>@item.TenDM</span></a></li>

                                        }

                                    </ul>
                                </li>
                                <li><a href=""><span>TIN TỨC</span></a></li>
                                <li><a href=""><span>GIỚI THIỆU</span></a></li>
                                <li><a href=""><span>LIÊN HỆ</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
        </div></div>
        <nav id="navbar" class="navbar order-last order-lg-0">


            <a class="nav-link scrollto search">
                <form>
                    <input type="text" id="keyword" name="txtKeyword" style="border-radius: 15px;" placeholder="Tìm kiếm ..." />
                    <i class="fas fa-search icons" style="font-size: 20px;margin-left: 0px;" onclick="onSearch()" ></i>
                </form>
            </a>

            


            <ul class="dropdown" style="margin-left: -20px;">
                <a href="#"><span><i class="fas fa-user icons"></i></span></a>
                <ul>
                    @if (Session["user"] == null)
                    {
                        <li>@Html.ActionLink("ĐĂNG NHẬP", "Login", "TaiKhoans")</li>
                        <li>@Html.ActionLink("ĐĂNG KÝ", "Register", "TaiKhoans")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("XEM THÔNG TIN CÁ NHÂN", "ThongTin", "TaiKhoans")</li>
                        <li>@Html.ActionLink("ĐĂNG XUẤT", "Logout", "TaiKhoans")</li>
                    }
                </ul>
            </ul>

            <a href="@Url.Action("Index","GioHang")"><i class="fas fa-cart-plus icons"></i> <span style="border-radius: 50%; height: 25px; width: 25px; background: #bbb; text-align: center; position: fixed; top: 18px; right: 106px; line-height:25px;">
   @ViewBag.SoLuongGioHang
</span></a>
            <!-- .navbar -->
            </nav>

 </header>
<script>
    const onSearch = () => {
      
        const keyword = document.getElementById("keyword").value;
        window.location = `/Hangs/Timkiem?keyword=${keyword}`;
    }
</script>

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Views/Shared/_Script.cshtml
<script src="~/wwwroot/assets/js/popper.js"></script>

<script src="~/wwwroot/assets/js/jquery.js"></script>

<script src="~/wwwroot/assets/js/bootstrap.js"></script>

<script src="~/wwwroot/assets/js/dropdown.js"></script>

<script src="~/wwwroot/assets/js/semantic.js"></script>

<script src="~/wwwroot/assets/js/owl.carousel.js"></script>

<script src="~/wwwroot/assets/js/swiper.min.js"></script>

<script src="~/wwwroot/assets/js/vejcustome.js"></script>

<script src="~/wwwroot/assets/js/counter.js"></script>


<script src="~/wwwroot/assets/js/main.js"></script>

<!-- JS -->
<script src="~/wwwroot/assets/vendor/aos/aos.js"></script>
<script src="~/wwwroot/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/wwwroot/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/wwwroot/assets/vendor/purecounter/purecounter.js"></script>
    <script src ="~/wwwroot/assets/vendor/swiper/swiper-bundle.min.js">
        </script>




    <script>
        var hoaanh = function (event) {
            alert("Sản phẩm này đã hết hàng vui lòng chọn sản phẩm khác !");
        }
    </script>

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Views/Shared/_Slider.cshtml
<section id="hero">
    <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

            <div class="carousel-item active"><img src="~/wwwroot/img/slide/slide_1.jpg" alt="" width="100%" height="100%"></div>
            <div class="carousel-item "><img src="~/wwwroot/img/slide/slide_2.jpg" alt="" width="100%" height="100%"></div>
            <div class="carousel-item "><img src="~/wwwroot/img/slide/slide_3.jpg" alt="" width="100%" height="100%"></div>
            <div class="carousel-item "><img src="~/wwwroot/img/slide/slide_4.jpg" alt="" width="100%" height="100%"></div>
            <div class="carousel-item "><img src="~/wwwroot/img/slide/slide_5.jpg" alt="" width="100%" height="100%"></div>
            <div class="carousel-item "><img src="~/wwwroot/img/slide/slide_6.jpg" alt="" width="100%" height="100%"></div>
        </div>

        <!-- Button slide -->
        <a class="carousel-control-prev" onclick="xinhgai(event)" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>
        <!-- End button slide -->

    </div>
</section>
@*<script>
        var xinhgai = function (event) {
            alert("Đó nha");
            /*let heroCarouselIndicators = select("#hero-carousel-indicators*/
            let heroCarouselItems = select('#heroCarousel .carousel-item', true);
            alert("Đó nha: " + heroCarouselItems.Count);
            heroCarouselItems.forEach((item, index) => {
                (index === 0) ?
                    heroCarouselIndicators.innerHTML += "<li data-bs-target='#heroCarousel' data-bs-slide-to='" + index + "' class='active'></li>" :
                    heroCarouselIndicators.innerHTML += "<li data-bs-target='#heroCarousel' data-bs-slide-to='" + index + "'></li>"
            });

        }

        let heroCarouselIndicators = select("#hero-carousel-indicators")
        let heroCarouselItems = select('#heroCarousel .carousel-item', true)

        heroCarouselItems.forEach((item, index) => {
            (index === 0) ?
                heroCarouselIndicators.innerHTML += "<li data-bs-target='#heroCarousel' data-bs-slide-to='" + index + "' class='active'></li>" :
                heroCarouselIndicators.innerHTML += "<li data-bs-target='#heroCarousel' data-bs-slide-to='" + index + "'></li>"
        });

    </script>*@

Nhom8_ShopMotoBikes/Nhom8_ShopMotoBikes/Views/Shared/_Style.cshtml
<link href="~/wwwroot/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/bootstrap.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/owl.carousel.css" rel="stylesheet" />

<link rel="stylesheet" href="~/wwwroot/assets/unicons/css/unicons.css" />

<link  href="~/wwwroot/css/style.css" rel="stylesheet" />

<link  href="~/wwwroot/css/responsive.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/semantic.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/animate.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/swiper.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">

<link href="~/wwwroot/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">

<!-- Fonts -->

<link href="~/wwwroot/assets/fonts/style.css" rel="stylesheet" />	

































<style>
    .store-pagination {
        text-align: left;
    }

        .store-pagination li {
            display: inline-block;
            width: 40px;
            height: 40px;
            line-height: 40px;
            text-align: center;
            background-color: #FFF;
            border: 1px solid #E4E7ED;
            -webkit-transition: 0.2s all;
            transition: 0.2s all;
            color: #2b2f4c;
        }

            .store-pagination li + li {
                margin-left: 5px;
            }

            .store-pagination li:hover {
                background-color: #F55D2C;
                border-color: #F55D2C;
                color: #FFF;
            }

            .store-pagination li.active {
                background-color: #F55D2C;
                border-color: #F55D2C;
                color: #FFF;
                font-weight: 500;
                cursor: default;
            }

            .store-pagination li a {
                display: block;
            }
</style>